# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/
  instance:
    preferIpAddress: true

zuul: 
  ignoredServices: "*" 
  routes: 
    CLIENT-SERVICE2: 
      path: /details/**
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
